import { User, Community, Post, Comment } from '@/types';

// 10 Mock users
export const mockUsers: User[] = [
  {
    id: 'user1',
    email: 'zhangsan@example.com',
    username: 'zhangsan',
    nickname: '张三',
    avatar: undefined,
    points: 1250,
    currentCar: '2019 BMW 330i G20，B48 发动机，2023年6月入手，日常代步 + 周末跑山',
    carHistory: 'E46 325i（2020-2022）→ E90 330i（2022-2023）→ G20 330i（至今）',
    expertise: 'JDM、德系老车、操控派、底盘调校',
    interests: '赛道日、自驾游、摄影、模型收藏',
    createdAt: new Date('2025-01-15'),
  },
  {
    id: 'user2',
    email: 'lisi@example.com',
    username: 'lisi',
    nickname: '李四',
    avatar: undefined,
    points: 580,
    currentCar: '2015 Mercedes-Benz C200 W205，2024年1月入手，原厂状态，纯代步',
    interests: '自驾游、钓鱼、汽车文化',
    createdAt: new Date('2025-03-20'),
  },
  {
    id: 'user3',
    email: 'wangwu@example.com',
    username: 'wangwu',
    nickname: '王五',
    avatar: undefined,
    points: 3200,
    currentCar: '2021 Porsche 718 Cayman，2.0T 水平对置，2023年9月入手，周末赛道日用',
    carHistory: '丰田86（2019-2020）→ 斯巴鲁BRZ（2020-2023）→ 保时捷718（至今）',
    expertise: '大排量自吸、赛道驾驶、涡轮升级',
    interests: '赛道日、汽车摄影、模型收藏、咖啡',
    createdAt: new Date('2024-11-10'),
  },
  {
    id: 'user4',
    email: 'zhaoliu@example.com',
    username: 'zhaoliu',
    nickname: '赵六',
    avatar: undefined,
    points: 890,
    currentCar: '2018 Audi A4L B9，2.0T EA888，2024年5月入手，日常代步',
    interests: '自驾游、汽车改装、摄影',
    createdAt: new Date('2025-05-01'),
  },
  {
    id: 'user5',
    email: 'sunqi@example.com',
    username: 'sunqi',
    nickname: '孙七',
    avatar: undefined,
    points: 2100,
    currentCar: '2020 Toyota GR Supra，B58 发动机，2022年3月入手，周末跑山利器',
    carHistory: '本田思域 FK5（2018-2019）→ 丰田86（2019-2022）→ GR Supra（至今）',
    expertise: 'JDM、日系性能车、操控派',
    interests: '跑山、赛道日、汽车模型、游戏',
    createdAt: new Date('2025-02-10'),
  },
  {
    id: 'user6',
    email: 'zhouba@example.com',
    username: 'zhouba',
    nickname: '周八',
    avatar: undefined,
    points: 450,
    currentCar: '2016 Honda Civic FK7，2025年2月入手，原厂状态，纯代步',
    interests: '汽车文化、自驾游、音乐',
    createdAt: new Date('2025-06-15'),
  },
  {
    id: 'user7',
    email: 'wujiu@example.com',
    username: 'wujiu',
    nickname: '吴九',
    avatar: undefined,
    points: 1680,
    currentCar: '2019 Volkswagen Golf GTI MK7.5，EA888 三代，2023年11月入手，小钢炮日常通勤',
    carHistory: '高尔夫6（2018-2020）→ GTI MK7（2020-2023）→ GTI MK7.5（至今）',
    expertise: '德系老车修复、EA888、小钢炮文化',
    interests: '自驾游、模型收藏、精酿啤酒',
    createdAt: new Date('2025-04-22'),
  },
  {
    id: 'user8',
    email: 'zhengshi@example.com',
    username: 'zhengshi',
    nickname: '郑十',
    avatar: undefined,
    points: 720,
    currentCar: '2022 Mazda CX-5，原厂 SUV，家用代步',
    interests: '自驾游、钓鱼、家庭用车心得分享',
    createdAt: new Date('2025-07-01'),
  },
  {
    id: 'user9',
    email: 'chenwei@example.com',
    username: 'chenwei',
    nickname: '陈伟',
    avatar: undefined,
    points: 4500,
    currentCar: '2018 Nissan GT-R R35，VR38DETT，周末赛道 + 收藏',
    carHistory: '日产 Silvia S15 → Skyline R34 → GT-R R35，日产性能车全家桶',
    expertise: '涡轮系统搭建、发动机大修、变速箱调校、空气动力学',
    interests: '赛道日、汽车收藏、机械表、雪茄',
    createdAt: new Date('2024-08-15'),
  },
  {
    id: 'user10',
    email: 'liufang@example.com',
    username: 'liufang',
    nickname: '刘芳',
    avatar: undefined,
    points: 320,
    createdAt: new Date('2025-08-20'),
  },
];

// Mock communities
export const mockCommunities: Community[] = [
  {
    id: 'comm1',
    slug: 'w221',
    brand: '奔驰',
    code: 'W221',
    displayName: 'W221',
    description: '奔驰 W221 底盘，第十代S级轿车（2005-2013），搭载M272/M273发动机',
    postCount: 156,
    memberCount: 892,
    createdAt: new Date('2025-01-01'),
    createdById: 'user1',
  },
  {
    id: 'comm2',
    slug: 'e46',
    brand: '宝马',
    code: 'E46',
    displayName: 'E46',
    description: '宝马 E46 底盘，第四代3系（1998-2006），经典直六M54发动机',
    postCount: 234,
    memberCount: 1456,
    createdAt: new Date('2025-01-05'),
    createdById: 'user2',
  },
  {
    id: 'comm3',
    slug: 'b58',
    brand: '宝马',
    code: 'B58',
    displayName: 'B58',
    description: '宝马 B58 发动机，新一代3.0T直列六缸涡轮增压',
    postCount: 89,
    memberCount: 567,
    createdAt: new Date('2025-02-10'),
    createdById: 'user1',
  },
  {
    id: 'comm4',
    slug: 'ea888',
    brand: '大众',
    code: 'EA888',
    displayName: 'EA888',
    description: '大众 EA888 发动机，集团主力2.0T，覆盖高尔夫GTI、奥迪A4等',
    postCount: 312,
    memberCount: 2103,
    createdAt: new Date('2025-01-08'),
    createdById: 'user3',
  },
  {
    id: 'comm5',
    slug: 'b8',
    brand: '奥迪',
    code: 'B8',
    displayName: 'B8',
    description: '奥迪 B8 底盘，第四代A4（2007-2015），MLB平台首款前驱/四驱布局',
    postCount: 178,
    memberCount: 945,
    createdAt: new Date('2025-01-12'),
    createdById: 'user2',
  },
  {
    id: 'comm6',
    slug: '2jz',
    brand: '丰田',
    code: '2JZ',
    displayName: '2JZ',
    description: '丰田 2JZ 发动机，传奇3.0T直列六缸，Supra JZA80 搭载',
    postCount: 445,
    memberCount: 3201,
    createdAt: new Date('2024-12-20'),
    createdById: 'user3',
  },
];

// Helper: days ago from now
function daysAgo(days: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d;
}

// Mock posts (12 posts across communities, by different users)
export const mockPosts: Post[] = [
  {
    id: 'post1',
    title: 'W221 入手半年心得，M272 发动机真的耐用吗？',
    content: '半年前入手了一台2008年的S350，目前跑了15万公里。说说我的用车感受...\n\n## 优点\n- 底盘质感依然是顶级\n- 空气悬挂虽然老但没漏气\n- M272 3.5L V6 动力够用\n\n## 需要注意的\n- 正时链条导板容易碎\n- 平衡轴齿轮磨损问题\n- 电子系统偶尔抽风',
    type: 'IMAGE',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=500&fit=crop'],
    communityId: 'comm1',
    authorId: 'user1',
    voteScore: 87,
    bookmarkCount: 23,
    commentCount: 15,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
    author: mockUsers[0],
    community: mockCommunities[0],
  },
  {
    id: 'post2',
    title: 'E46 330i 改装分享：回归驾驶乐趣',
    content: '刚完成的改装项目：\n\n- BC Racing 绞牙避震\n- 17寸 Style 68 轮毂\n- 进气升级 BMC 风格\n- 排气改中段直通\n\n驾驶感受提升非常明显，弯道支撑性好了很多。',
    type: 'IMAGE',
    images: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1583121274602-3e2820c6914a?w=800&h=500&fit=crop'],
    communityId: 'comm2',
    authorId: 'user2',
    voteScore: 156,
    bookmarkCount: 45,
    commentCount: 28,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    author: mockUsers[1],
    community: mockCommunities[1],
  },
  {
    id: 'post3',
    title: 'EA888 Gen3 烧机油解决方案汇总',
    content: 'EA888 第三代烧机油问题比前两代好很多，但还是有些车主会遇到。这里汇总几个常见解决方案：\n\n1. 检查油气分离器\n2. 更换改进型活塞环\n3. 使用粘度更高的机油 5W-40\n4. 定期清洁进气道积碳',
    type: 'IMAGE',
    images: ['https://images.unsplash.com/photo-1606664515524-ed2f65f84f5a?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1619405399517-d7fce0f130b2?w=800&h=500&fit=crop'],
    communityId: 'comm4',
    authorId: 'user3',
    voteScore: 234,
    bookmarkCount: 89,
    commentCount: 42,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
    author: mockUsers[2],
    community: mockCommunities[3],
  },
  {
    id: 'post4',
    title: 'B58 vs 2JZ：谁才是最强直六？',
    content: '这是一个很有争议的话题。两台发动机我都开过，来做个详细对比...\n\nB58 优势：轻量化、热效率高、改装潜力大\n2JZ 优势：铸铁缸体、高增压耐受力强、传奇可靠性',
    type: 'LINK',
    url: 'https://example.com/b58-vs-2jz',
    communityId: 'comm3',
    authorId: 'user1',
    voteScore: 312,
    bookmarkCount: 67,
    commentCount: 56,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    author: mockUsers[0],
    community: mockCommunities[2],
  },
  {
    id: 'post5',
    title: '奥迪 B8 底盘异响排查全过程',
    content: '最近我的 A4 B8 过减速带时前悬挂有"咯噔"声，去检查发现是上控制臂球头松旷。\n\nB8 的前悬挂是五连杆结构，球头磨损是通病。换了两个上控制臂，问题解决。\n\n费用：原厂件 1800/根，工时费 600。',
    type: 'IMAGE',
    images: ['https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&h=500&fit=crop'],
    communityId: 'comm5',
    authorId: 'user4',
    voteScore: 67,
    bookmarkCount: 18,
    commentCount: 9,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
    author: mockUsers[3],
    community: mockCommunities[4],
  },
  {
    id: 'post6',
    title: '2JZ 千匹改装记录：从 300 到 1000 匹',
    content: '历时三个月，终于完成了 2JZ-GTE 的千匹改装。\n\n核心改装件：\n- Precision 6766 涡轮\n- Haltech Elite 2500 ECU\n- ID2200 喷油器\n- 强化锻造活塞连杆\n\nDyno 实测：轮上 980 匹 @ 2.2bar',
    type: 'IMAGE',
    images: ['https://images.unsplash.com/photo-1626668011687-8a114cf5a34c?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&h=500&fit=crop'],
    communityId: 'comm6',
    authorId: 'user9',
    voteScore: 523,
    bookmarkCount: 134,
    commentCount: 67,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    author: mockUsers[8],
    community: mockCommunities[5],
  },
  {
    id: 'post7',
    title: '新手求问：高尔夫 MK7 GTI 值不值得入？',
    content: '预算15万左右，想入一台二手 MK7 GTI。主要日常代步，偶尔跑跑山路。\n\n请问各位大佬：\n1. 哪一年的比较靠谱？\n2. EA888 Gen3 可靠性怎么样？\n3. DSG 变速箱有没有通病？',
    type: 'IMAGE',
    images: ['https://images.unsplash.com/photo-1619405399517-d7fce0f130b2?w=800&h=500&fit=crop'],
    communityId: 'comm4',
    authorId: 'user10',
    voteScore: 45,
    bookmarkCount: 12,
    commentCount: 23,
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
    author: mockUsers[9],
    community: mockCommunities[3],
  },
  {
    id: 'post8',
    title: 'E46 翻新日记：让 20 年的老车重获新生',
    content: '收了一台 2003 年的 325i，里程 22 万公里。准备做一次全面翻新。\n\n计划项目：\n- 全车喷漆\n- 内饰翻新\n- 发动机大修\n- 底盘件全部更换\n\n会持续更新进度！',
    type: 'IMAGE',
    images: ['https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1583121274602-3e2820c6914a?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=500&fit=crop'],
    communityId: 'comm2',
    authorId: 'user5',
    voteScore: 198,
    bookmarkCount: 56,
    commentCount: 34,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
    author: mockUsers[4],
    community: mockCommunities[1],
  },
  {
    id: 'post9',
    title: '奔驰 W222 空气悬挂维修经验分享',
    content: 'W222 的空气悬挂到了10万公里基本都要出问题。\n\n我的 S400L 右前气囊漏气了，4S 报价 2.8 万一根。\n\n后来找了专修店换了 Arnott 副厂件，5500 搞定，质量很不错，推荐。',
    type: 'IMAGE',
    images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=500&fit=crop'],
    communityId: 'comm1',
    authorId: 'user7',
    voteScore: 134,
    bookmarkCount: 41,
    commentCount: 18,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    author: mockUsers[6],
    community: mockCommunities[0],
  },
  {
    id: 'post10',
    title: '保时捷 997.2 Carrera S 提车作业',
    content: '终于实现了梦想，提了一台 2010 年的 997.2 Carrera S。\n\nPDK 变速箱 + Sport Chrono 组件，选装清单很长。\n\n这代 911 是最经典的形态，开起来也是最纯粹的。',
    type: 'IMAGE',
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&h=500&fit=crop'],
    communityId: 'comm3',
    authorId: 'user6',
    voteScore: 267,
    bookmarkCount: 78,
    commentCount: 31,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
    author: mockUsers[5],
    community: mockCommunities[2],
  },
  {
    id: 'post11',
    title: 'B58 一阶程序实测：0-100 提升多少？',
    content: '给我的 G20 340i 刷了一阶程序，实测数据分享：\n\n原厂：0-100 4.8s\n一阶后：0-100 4.2s\n\n马力从 374 提升到 430，扭矩从 500 提升到 580。\n\n感受：低扭明显增强，推背感更强。',
    type: 'IMAGE',
    images: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1583121274602-3e2820c6914a?w=800&h=500&fit=crop'],
    communityId: 'comm3',
    authorId: 'user8',
    voteScore: 189,
    bookmarkCount: 52,
    commentCount: 27,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
    author: mockUsers[7],
    community: mockCommunities[2],
  },
  {
    id: 'post12',
    title: '2JZ 和 RB26 到底选哪个？',
    content: '准备入一台日系性能车，纠结是选 Supra JZA80（2JZ）还是 Skyline R34 GT-R（RB26）。\n\n两台都是传奇发动机，但定位不太一样：\n- 2JZ：直六涡轮，改装潜力大\n- RB26：直六双涡轮，四驱加持\n\n各位怎么看？',
    type: 'TEXT',
    communityId: 'comm6',
    authorId: 'user5',
    voteScore: 298,
    bookmarkCount: 89,
    commentCount: 45,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    author: mockUsers[4],
    community: mockCommunities[5],
  },
  // Trade posts
  {
    id: 'post13',
    title: '出 E46 M3 CSL 原厂排气中尾段',
    content: '换装 aftermarket 排气后拆下来的原厂中尾段，使用约 2 万公里，无磕碰无锈蚀。\n\n包含：\n- 中段管路\n- 尾消声器\n- 全套安装垫片和卡箍\n\n顺丰包邮，不议价。',
    type: 'TRADE',
    price: '2800',
    images: ['https://images.unsplash.com/photo-1606664515524-ed2f65f84f5a?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&h=500&fit=crop'],
    communityId: 'comm2',
    authorId: 'user3',
    voteScore: 34,
    bookmarkCount: 12,
    commentCount: 8,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    author: mockUsers[2],
    community: mockCommunities[1],
  },
  {
    id: 'post14',
    title: '出 2006 款 BMW E46 330Ci，手动挡，原版原漆',
    content: '个人一手车，2006 年上牌，行驶 14.8 万公里。\n\n车况：\n- M54B30 发动机，运行平稳，无渗油\n- 5 速手动变速箱，换挡顺滑\n- 原版原漆，无事故\n- 内饰磨损轻微\n- 年检到 2026 年 12 月\n\n坐标上海，可过户。',
    type: 'TRADE',
    price: '68000',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&h=500&fit=crop'],
    communityId: 'comm2',
    authorId: 'user5',
    voteScore: 89,
    bookmarkCount: 34,
    commentCount: 19,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    author: mockUsers[4],
    community: mockCommunities[1],
  },
  {
    id: 'post15',
    title: '出 B58 原厂涡轮 + 中冷器总成',
    content: '从 G20 340i 上拆下来的原厂涡轮和中冷器，升级大涡轮后闲置。\n\n涡轮型号：MHI TD04-13T\n中冷：原厂风冷\n\n使用里程约 3 万公里，无故障码，运转正常。\n适合原厂替换或一阶改装基础件。',
    type: 'TRADE',
    price: '12000',
    images: ['https://images.unsplash.com/photo-1606664515524-ed2f65f84f5a?w=800&h=500&fit=crop'],
    communityId: 'comm3',
    authorId: 'user9',
    voteScore: 56,
    bookmarkCount: 21,
    commentCount: 14,
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
    author: mockUsers[8],
    community: mockCommunities[2],
  },
];

// Mock comments (rich cross-commenting between 10 users)
export const mockComments: Comment[] = [
  // Comments on post1 (W221 心得)
  {
    id: 'comment1',
    content: 'M272 的正时链条确实是个通病，建议10万公里左右检查一次。我的S350在12万公里时换的。',
    postId: 'post1',
    parentId: undefined,
    authorId: 'user2',
    author: mockUsers[1],
    voteScore: 23,
    createdAt: daysAgo(3),
  },
  {
    id: 'comment2',
    content: '同意楼上，另外平衡轴齿轮也建议一起检查，零件不贵但工时费很高。',
    postId: 'post1',
    parentId: 'comment1',
    authorId: 'user3',
    author: mockUsers[2],
    voteScore: 15,
    createdAt: daysAgo(3),
  },
  {
    id: 'comment3',
    content: '请问换正时链条大概多少费用？我这边4S报价要2万多...',
    postId: 'post1',
    parentId: 'comment1',
    authorId: 'user1',
    author: mockUsers[0],
    voteScore: 8,
    createdAt: daysAgo(2),
  },
  {
    id: 'comment4',
    content: '去靠谱的专修店换，大概8000-12000搞定，没必要去4S。',
    postId: 'post1',
    parentId: 'comment3',
    authorId: 'user2',
    author: mockUsers[1],
    voteScore: 19,
    createdAt: daysAgo(2),
  },
  {
    id: 'comment5',
    content: '我去年也入手了W221 S400，底盘质感确实没话说。不过我的空气悬挂已经开始漏气了😂',
    postId: 'post1',
    parentId: undefined,
    authorId: 'user7',
    author: mockUsers[6],
    voteScore: 12,
    createdAt: daysAgo(2),
  },
  {
    id: 'comment6',
    content: '可以看看 Arnott 的副厂件，性价比高，我换了一年多了没问题。',
    postId: 'post1',
    parentId: 'comment5',
    authorId: 'user4',
    author: mockUsers[3],
    voteScore: 9,
    createdAt: daysAgo(2),
  },

  // Comments on post2 (E46 改装)
  {
    id: 'comment7',
    content: 'Style 68 配 E46 太好看了！请问轮毂数据是多少？ET 值多少？',
    postId: 'post2',
    parentId: undefined,
    authorId: 'user5',
    author: mockUsers[4],
    voteScore: 34,
    createdAt: daysAgo(1),
  },
  {
    id: 'comment8',
    content: '前 17x8 ET30 后 17x9 ET35，刚好齐平翼子板。',
    postId: 'post2',
    parentId: 'comment7',
    authorId: 'user2',
    author: mockUsers[1],
    voteScore: 28,
    createdAt: daysAgo(1),
  },
  {
    id: 'comment9',
    content: 'BC 避震用了多久？有没有异响问题？我之前用了一套半年就漏油了。',
    postId: 'post2',
    parentId: undefined,
    authorId: 'user9',
    author: mockUsers[8],
    voteScore: 18,
    createdAt: daysAgo(1),
  },
  {
    id: 'comment10',
    content: 'BC 的品控确实参差不齐，建议考虑 KW V3，虽然贵但品质有保障。',
    postId: 'post2',
    parentId: 'comment9',
    authorId: 'user3',
    author: mockUsers[2],
    voteScore: 22,
    createdAt: daysAgo(0),
  },
  {
    id: 'comment11',
    content: 'E46 的 M54 发动机也很经典，日常保养到位的话跑30万公里没问题。',
    postId: 'post2',
    parentId: undefined,
    authorId: 'user6',
    author: mockUsers[5],
    voteScore: 15,
    createdAt: daysAgo(0),
  },

  // Comments on post3 (EA888 烧机油)
  {
    id: 'comment12',
    content: 'Gen3 已经比 Gen2 好太多了，我的 MK7 GTI 跑了8万公里基本不烧。关键是要用对机油。',
    postId: 'post3',
    parentId: undefined,
    authorId: 'user4',
    author: mockUsers[3],
    voteScore: 45,
    createdAt: daysAgo(5),
  },
  {
    id: 'comment13',
    content: '推荐用什么机油？我现在用的嘉实多极护 5W-30。',
    postId: 'post3',
    parentId: 'comment12',
    authorId: 'user10',
    author: mockUsers[9],
    voteScore: 8,
    createdAt: daysAgo(4),
  },
  {
    id: 'comment14',
    content: '建议换力魔 5W-40 或者美孚1号 ESP 5W-30，VW 504/507 认证的。',
    postId: 'post3',
    parentId: 'comment12',
    authorId: 'user3',
    author: mockUsers[2],
    voteScore: 38,
    createdAt: daysAgo(4),
  },
  {
    id: 'comment15',
    content: '进气道积碳清洗建议多少公里做一次？我车已经6万公里了。',
    postId: 'post3',
    parentId: undefined,
    authorId: 'user8',
    author: mockUsers[7],
    voteScore: 16,
    createdAt: daysAgo(4),
  },
  {
    id: 'comment16',
    content: '一般4-6万公里清洗一次就行，核桃砂清洗效果最好，大概1500-2000块。',
    postId: 'post3',
    parentId: 'comment15',
    authorId: 'user3',
    author: mockUsers[2],
    voteScore: 27,
    createdAt: daysAgo(3),
  },

  // Comments on post4 (B58 vs 2JZ)
  {
    id: 'comment17',
    content: '2JZ 铸铁缸体可以承受更高的增压值，千匹改装轻轻松松。B58 虽然先进，但极限不如 2JZ。',
    postId: 'post4',
    parentId: undefined,
    authorId: 'user9',
    author: mockUsers[8],
    voteScore: 56,
    createdAt: daysAgo(2),
  },
  {
    id: 'comment18',
    content: '不同意，B58 原厂就能跑 4.5 秒破百，改装到 600 匹也很稳定。2JZ 要千匹才有意义。',
    postId: 'post4',
    parentId: undefined,
    authorId: 'user5',
    author: mockUsers[4],
    voteScore: 43,
    createdAt: daysAgo(2),
  },
  {
    id: 'comment19',
    content: '日常驾驶肯定 B58 更合适，赛道和直线加速选 2JZ。两台都是好机器，看使用场景。',
    postId: 'post4',
    parentId: undefined,
    authorId: 'user7',
    author: mockUsers[6],
    voteScore: 67,
    createdAt: daysAgo(1),
  },
  {
    id: 'comment20',
    content: '楼上说得好，定位不同没必要非得分高下。',
    postId: 'post4',
    parentId: 'comment19',
    authorId: 'user1',
    author: mockUsers[0],
    voteScore: 21,
    createdAt: daysAgo(1),
  },

  // Comments on post5 (奥迪 B8 底盘)
  {
    id: 'comment21',
    content: 'B8 的五连杆前悬确实吃球头，我的 A4 也换过了。建议用 Lemforder 的件，OEM 品质。',
    postId: 'post5',
    parentId: undefined,
    authorId: 'user3',
    author: mockUsers[2],
    voteScore: 19,
    createdAt: daysAgo(3),
  },
  {
    id: 'comment22',
    content: '我 B8.5 的也有这个问题，请问换完需要做四轮定位吗？',
    postId: 'post5',
    parentId: 'comment21',
    authorId: 'user8',
    author: mockUsers[7],
    voteScore: 7,
    createdAt: daysAgo(3),
  },
  {
    id: 'comment23',
    content: '必须做，换了控制臂后前束和外倾角都会变。',
    postId: 'post5',
    parentId: 'comment21',
    authorId: 'user4',
    author: mockUsers[3],
    voteScore: 14,
    createdAt: daysAgo(3),
  },

  // Comments on post6 (2JZ 千匹)
  {
    id: 'comment24',
    content: '太强了！轮上 980 匹是什么概念？0-400 米能跑多少？',
    postId: 'post6',
    parentId: undefined,
    authorId: 'user1',
    author: mockUsers[0],
    voteScore: 34,
    createdAt: daysAgo(1),
  },
  {
    id: 'comment25',
    content: '轮上 980 匹配 Nitto NT05R 的话，0-400 大概 8 秒出头。',
    postId: 'post6',
    parentId: 'comment24',
    authorId: 'user9',
    author: mockUsers[8],
    voteScore: 45,
    createdAt: daysAgo(0),
  },
  {
    id: 'comment26',
    content: 'Haltech 的 ECU 调起来方便吗？我准备给 RB26 也换一个。',
    postId: 'post6',
    parentId: undefined,
    authorId: 'user5',
    author: mockUsers[4],
    voteScore: 18,
    createdAt: daysAgo(0),
  },
  {
    id: 'comment27',
    content: 'Haltech 软件很直观，支持自动调校功能。RB26 用 Link ECU 的也很多，你可以对比下。',
    postId: 'post6',
    parentId: 'comment26',
    authorId: 'user9',
    author: mockUsers[8],
    voteScore: 22,
    createdAt: daysAgo(0),
  },
  {
    id: 'comment28',
    content: '千匹 2JZ，男人的梦想！请问总花费大概多少？',
    postId: 'post6',
    parentId: undefined,
    authorId: 'user6',
    author: mockUsers[5],
    voteScore: 15,
    createdAt: daysAgo(0),
  },

  // Comments on post7 (MK7 GTI 求问)
  {
    id: 'comment29',
    content: '推荐 2017-2018 年的，Gen3 EA888 已经改进了很多。注意检查 DSG 换挡是否平顺。',
    postId: 'post7',
    parentId: undefined,
    authorId: 'user3',
    author: mockUsers[2],
    voteScore: 32,
    createdAt: daysAgo(0),
  },
  {
    id: 'comment30',
    content: 'DSG DQ250 六速湿式很可靠，按时换油就行。DQ380 七速早期批次有点问题。',
    postId: 'post7',
    parentId: undefined,
    authorId: 'user4',
    author: mockUsers[3],
    voteScore: 28,
    createdAt: daysAgo(0),
  },
  {
    id: 'comment31',
    content: '15 万的预算建议直接上 MK7.5，配置更好，发动机也更新了。',
    postId: 'post7',
    parentId: undefined,
    authorId: 'user7',
    author: mockUsers[6],
    voteScore: 19,
    createdAt: daysAgo(0),
  },
  {
    id: 'comment32',
    content: '谢谢各位大佬！决定入手 MK7.5 了，明天去看车 🎉',
    postId: 'post7',
    parentId: 'comment31',
    authorId: 'user10',
    author: mockUsers[9],
    voteScore: 12,
    createdAt: daysAgo(0),
  },

  // Comments on post8 (E46 翻新)
  {
    id: 'comment33',
    content: 'E46 翻新太有意义了！期待持续更新。发动机大修打算换什么？',
    postId: 'post8',
    parentId: undefined,
    authorId: 'user2',
    author: mockUsers[1],
    voteScore: 25,
    createdAt: daysAgo(5),
  },
  {
    id: 'comment34',
    content: '打算换 VANOS 单元、气门油封、正时链条导板，顺便把缸盖垫片也换了。',
    postId: 'post8',
    parentId: 'comment33',
    authorId: 'user5',
    author: mockUsers[4],
    voteScore: 31,
    createdAt: daysAgo(5),
  },

  // Comments on post9 (W222 空悬)
  {
    id: 'comment35',
    content: 'Arnott 确实不错，我 W221 也换的 Arnott，比原厂便宜 80%。',
    postId: 'post9',
    parentId: undefined,
    authorId: 'user1',
    author: mockUsers[0],
    voteScore: 23,
    createdAt: daysAgo(2),
  },
  {
    id: 'comment36',
    content: '请问 Arnott 在哪买的？有靠谱的渠道推荐吗？',
    postId: 'post9',
    parentId: 'comment35',
    authorId: 'user6',
    author: mockUsers[5],
    voteScore: 11,
    createdAt: daysAgo(1),
  },

  // Comments on post10 (997 提车)
  {
    id: 'comment37',
    content: '997.2 是最后一代液压助力的 911 了吧？转向手感无敌！',
    postId: 'post10',
    parentId: undefined,
    authorId: 'user9',
    author: mockUsers[8],
    voteScore: 41,
    createdAt: daysAgo(3),
  },
  {
    id: 'comment38',
    content: '恭喜提车！PDK 在 997.2 上已经很成熟了，换挡速度比手动快太多。',
    postId: 'post10',
    parentId: undefined,
    authorId: 'user7',
    author: mockUsers[6],
    voteScore: 29,
    createdAt: daysAgo(2),
  },
  {
    id: 'comment39',
    content: '选装清单能分享一下吗？Sport Chrono 是必选的。',
    postId: 'post10',
    parentId: undefined,
    authorId: 'user8',
    author: mockUsers[7],
    voteScore: 16,
    createdAt: daysAgo(2),
  },

  // Comments on post11 (B58 一阶)
  {
    id: 'comment40',
    content: '4.2 秒破百！这数据已经很快了。请问刷的哪家的程序？',
    postId: 'post11',
    parentId: undefined,
    authorId: 'user1',
    author: mockUsers[0],
    voteScore: 22,
    createdAt: daysAgo(3),
  },
  {
    id: 'comment41',
    content: 'Bootmod3，B58 上最成熟的程序之一。二阶加排气能到 480 匹。',
    postId: 'post11',
    parentId: 'comment40',
    authorId: 'user8',
    author: mockUsers[7],
    voteScore: 35,
    createdAt: daysAgo(3),
  },

  // Comments on post12 (2JZ vs RB26)
  {
    id: 'comment42',
    content: '选 2JZ，后驱更有驾驶乐趣。RB26 的 GT-R 虽然快但少了一些沟通感。',
    postId: 'post12',
    parentId: undefined,
    authorId: 'user9',
    author: mockUsers[8],
    voteScore: 56,
    createdAt: daysAgo(1),
  },
  {
    id: 'comment43',
    content: '不同意，R34 GT-R 的 ATTESA E-TS 四驱系统是艺术品，弯道稳定性无敌。',
    postId: 'post12',
    parentId: undefined,
    authorId: 'user5',
    author: mockUsers[4],
    voteScore: 48,
    createdAt: daysAgo(1),
  },
  {
    id: 'comment44',
    content: '两台都是 JDM 传奇，看预算吧。R34 GT-R 现在价格已经上天了。',
    postId: 'post12',
    parentId: undefined,
    authorId: 'user3',
    author: mockUsers[2],
    voteScore: 37,
    createdAt: daysAgo(0),
  },
  {
    id: 'comment45',
    content: '确实，R34 GT-R 现在要 200 万以上了，Supra JZA80 相对还便宜点。',
    postId: 'post12',
    parentId: 'comment44',
    authorId: 'user6',
    author: mockUsers[5],
    voteScore: 19,
    createdAt: daysAgo(0),
  },
];

// Preset car models for community creation
export const presetCarModels = [
  // 奔驰
  { slug: 'w221', brand: '奔驰', code: 'W221', displayName: '奔驰 W221 (S级 2005-2013)' },
  { slug: 'w222', brand: '奔驰', code: 'W222', displayName: '奔驰 W222 (S级 2013-2020)' },
  { slug: 'w206', brand: '奔驰', code: 'W206', displayName: '奔驰 W206 (C级 2021-)' },
  { slug: 'm272', brand: '奔驰', code: 'M272', displayName: '奔驰 M272 发动机' },
  { slug: 'm276', brand: '奔驰', code: 'M276', displayName: '奔驰 M276 发动机' },
  { slug: 'm156', brand: '奔驰', code: 'M156', displayName: '奔驰 M156 (AMG 6.2L V8)' },
  // 宝马
  { slug: 'e46', brand: '宝马', code: 'E46', displayName: '宝马 E46 (3系 1998-2006)' },
  { slug: 'e90', brand: '宝马', code: 'E90', displayName: '宝马 E90 (3系 2005-2012)' },
  { slug: 'f30', brand: '宝马', code: 'F30', displayName: '宝马 F30 (3系 2012-2019)' },
  { slug: 'g20', brand: '宝马', code: 'G20', displayName: '宝马 G20 (3系 2019-)' },
  { slug: 'b58', brand: '宝马', code: 'B58', displayName: '宝马 B58 发动机' },
  { slug: 'n54', brand: '宝马', code: 'N54', displayName: '宝马 N54 发动机' },
  { slug: 's58', brand: '宝马', code: 'S58', displayName: '宝马 S58 (M Power)' },
  // 奥迪
  { slug: 'b8', brand: '奥迪', code: 'B8', displayName: '奥迪 B8 (A4 2007-2015)' },
  { slug: 'b9', brand: '奥迪', code: 'B9', displayName: '奥迪 B9 (A4 2015-)' },
  { slug: 'c7', brand: '奥迪', code: 'C7', displayName: '奥迪 C7 (A6 2011-2018)' },
  { slug: 'ea888', brand: '奥迪', code: 'EA888', displayName: '大众/奥迪 EA888 发动机' },
  { slug: 'ea855', brand: '奥迪', code: 'EA855', displayName: '奥迪 EA855 (2.5T 直五)' },
  // 大众
  { slug: 'mk7', brand: '大众', code: 'MK7', displayName: '大众高尔夫 MK7' },
  { slug: 'mk8', brand: '大众', code: 'MK8', displayName: '大众高尔夫 MK8' },
  { slug: 'ea113', brand: '大众', code: 'EA113', displayName: '大众 EA113 发动机' },
  // 丰田
  { slug: '2jz', brand: '丰田', code: '2JZ', displayName: '丰田 2JZ 发动机' },
  { slug: '1jz', brand: '丰田', code: '1JZ', displayName: '丰田 1JZ 发动机' },
  { slug: 'gr86', brand: '丰田', code: 'GR86', displayName: '丰田 GR86' },
  { slug: 'supra-a90', brand: '丰田', code: 'Supra_A90', displayName: '丰田 Supra A90' },
  // 本田
  { slug: 'k20', brand: '本田', code: 'K20', displayName: '本田 K20 发动机' },
  { slug: 'b16', brand: '本田', code: 'B16', displayName: '本田 B16 发动机' },
  { slug: 'type-r-fl5', brand: '本田', code: 'TypeR_FL5', displayName: '本田 Civic Type R FL5' },
  // 日产
  { slug: 'rb26', brand: '日产', code: 'RB26', displayName: '日产 RB26 发动机' },
  { slug: 'vr38', brand: '日产', code: 'VR38', displayName: '日产 VR38 (GT-R)' },
  { slug: 'r35', brand: '日产', code: 'R35', displayName: '日产 GT-R R35' },
  // 马自达
  { slug: 'rx7-fd', brand: '马自达', code: 'RX7_FD', displayName: '马自达 RX-7 FD' },
  { slug: '13b', brand: '马自达', code: '13B', displayName: '马自达 13B 转子发动机' },
  { slug: 'mx5-nd', brand: '马自达', code: 'MX5_ND', displayName: '马自达 MX-5 ND' },
  // 保时捷
  { slug: '997', brand: '保时捷', code: '997', displayName: '保时捷 911 997' },
  { slug: '992', brand: '保时捷', code: '992', displayName: '保时捷 911 992' },
  { slug: 'cayman-981', brand: '保时捷', code: 'Cayman_981', displayName: '保时捷 Cayman 981' },
  // 斯巴鲁
  { slug: 'ej20', brand: '斯巴鲁', code: 'EJ20', displayName: '斯巴鲁 EJ20 发动机' },
  { slug: 'ej25', brand: '斯巴鲁', code: 'EJ25', displayName: '斯巴鲁 EJ25 发动机' },
  { slug: 'wrx-va', brand: '斯巴鲁', code: 'WRX_VA', displayName: '斯巴鲁 WRX VA' },
  // 福特
  { slug: 'mustang-s550', brand: '福特', code: 'Mustang_S550', displayName: '福特 Mustang S550' },
  { slug: 'ecoboost', brand: '福特', code: 'EcoBoost', displayName: '福特 EcoBoost 发动机' },
];
